# Generated by Django 3.1 on 2020-10-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prize',
            name='price_for_top_winners',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='price_per_kill',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='winner_price',
        ),
        migrations.AddField(
            model_name='prize',
            name='price',
            field=models.FloatField(blank=True, help_text='Price', null=True),
        ),
    ]
