# Generated by Django 3.1 on 2020-10-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20201005_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='price_for_top_winners',
            field=models.FloatField(blank=True, help_text='Price for top players', null=True),
        ),
    ]
