# Generated by Django 3.1 on 2020-10-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('coremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.coremodel')),
                ('token', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('accounts.coremodel',),
        ),
    ]
